console.log('products.js loaded');
const products = {
    "Decrypted User Data|Données utilisateur décryptées": { economy: "trading", sellTo: ["Advanced Materials", "Scientific"], avgPrice: 15000 },
    "Star Silk|Soie stellaire": { economy: "trading", sellTo: ["Advanced Materials", "Scientific"], avgPrice: 12000 },
    "Comet Droplets|Gouttelettes de comète": { economy: "trading", sellTo: ["Advanced Materials", "Scientific"], avgPrice: 18000 },
    "Ion Sphere|Sphère ionique": { economy: "trading", sellTo: ["Advanced Materials", "Scientific"], avgPrice: 20000 },
    "Superconducting Fibre|Fibre supraconductrice": { economy: "trading", sellTo: ["Advanced Materials", "Scientific"], avgPrice: 25000 },
    "Neural Duct|Conduit neuronal": { economy: "materials", sellTo: ["Scientific"], avgPrice: 8000 },
    "Self-Repairing Heridium|Héridium autoréparant": { economy: "materials", sellTo: ["Scientific"], avgPrice: 10000 },
    "Optical Solvent|Solvant optique": { economy: "materials", sellTo: ["Scientific"], avgPrice: 6000 },
    "Five Dimensional Torus|Torus pentadimensionnel": { economy: "materials", sellTo: ["Scientific"], avgPrice: 30000 },
    "Superluminal Drive|Propulseur superluminal": { economy: "materials", sellTo: ["Scientific"], avgPrice: 40000 },
    "De-Scented Pheromone Bottle|Bouteille de phéromones désodorisée": { economy: "scientific", sellTo: ["Trading"], avgPrice: 9000 },
    "Neural Transmitter|Transmetteur neuronal": { economy: "scientific", sellTo: ["Trading"], avgPrice: 11000 },
    "Organic Piping|Tuyauterie organique": { economy: "scientific", sellTo: ["Trading"], avgPrice: 7000 },
    "Instability Injector|Injecteur d’instabilité": { economy: "scientific", sellTo: ["Trading"], avgPrice: 13000 },
    "Teleport Coordinators|Coordinateurs de téléportation": { economy: "scientific", sellTo: ["Trading"], avgPrice: 15000 },
    "Ion Battery|Batterie ionique": { economy: "mining", sellTo: ["Manufacturing"], avgPrice: 5000 },
    "Dirt|Terre": { economy: "mining", sellTo: ["Manufacturing"], avgPrice: 20 },
    "Unrefined Pyrite Grease|Graisse de pyrite non raffinée": { economy: "mining", sellTo: ["Manufacturing"], avgPrice: 3000 },
    "Bromide Salt|Sel de bromure": { economy: "mining", sellTo: ["Manufacturing"], avgPrice: 4000 },
    "Polychromatic Zirconium|Zirconium polychromatique": { economy: "mining", sellTo: ["Manufacturing"], avgPrice: 6000 },
    "Nanotube Crate|Caisse de nanotubes": { economy: "manufacturing", sellTo: ["Technology"], avgPrice: 10000 },
    "Self-Repairing Component|Composant autoréparant": { economy: "manufacturing", sellTo: ["Technology"], avgPrice: 12000 },
    "Fusion Device|Dispositif de fusion": { economy: "manufacturing", sellTo: ["Technology"], avgPrice: 18000 },
    "Holographic Crankshaft|Vilebrequin holographique": { economy: "manufacturing", sellTo: ["Technology"], avgPrice: 15000 },
    "High-Pressure Gel|Gel haute pression": { economy: "manufacturing", sellTo: ["Technology"], avgPrice: 9000 },
    "Welding Soap|Savon de soudure": { economy: "technology", sellTo: ["Power Generation"], avgPrice: 7000 },
    "Enormous Metal Cog|Engrenage métallique énorme": { economy: "technology", sellTo: ["Power Generation"], avgPrice: 8000 },
    "Non-Stick Piston|Piston antiadhésif": { economy: "technology", sellTo: ["Power Generation"], avgPrice: 6000 },
    "Quantum Accelerator|Accélérateur quantique": { economy: "technology", sellTo: ["Power Generation"], avgPrice: 20000 },
    "Spark Canister|Bidon d’étincelles": { economy: "technology", sellTo: ["Power Generation"], avgPrice: 5000 },
    "Experimental Power Fluid|Fluide énergétique expérimental": { economy: "power", sellTo: ["Mining"], avgPrice: 10000 },
    "Industrial-Grade Battery|Batterie industrielle": { economy: "power", sellTo: ["Mining"], avgPrice: 12000 },
    "Ohmic Gel|Gel ohmique": { economy: "power", sellTo: ["Mining"], avgPrice: 8000 },
    "Experimental Force Shield|Bouclier de force expérimental": { economy: "power", sellTo: ["Mining"], avgPrice: 15000 },
    "Fusion Core|Cœur de fusion": { economy: "power", sellTo: ["Mining"], avgPrice: 20000 }
};