name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Clean old Cordova project
      run: rm -rf nms-app

    - name: Create Cordova project
      run: cordova create nms-app com.nmstrading.app "NMS Trading"

    - name: Copy all www files
      run: cp -R ./www/* nms-app/www/

    - name: Copy config.xml
      run: cp config.xml nms-app/

    - name: Add Android platform
      working-directory: ./nms-app
      run: |
        cordova platform add android
        cordova prepare android

    - name: Build Android APK
      working-directory: ./nms-app
      run: cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: nms-trading-apk
        path: nms-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
