name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g cordova
    - run: cordova platform add android
    - run: cordova build android
    - uses: actions/upload-artifact@v2
      with:
        name: apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
